baseURL = 'https://methexisstudio.com/'
languageCode = 'en-us'
title = 'Methexis Studio'
theme = 'blackwork'

publishDir = 'docs'

buildFuture = true

[markup]
  [markup.asciidocExt]
    safeMode = 'unsafe'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true




[_build]
  publishResources = false


[params]
  background = "alder_2_adj.png"
  header_main = "header.svg"
  header = "header_wide.svg"
  header_href = "/"
  bar = "bar.svg"

  navbar_pages = [
    {name = "Icons", url = ""},
    {name = "Cards", url = ""},
    {name = "Furniture", url = ""},
    {name = "Zines", url = ""}
  ]

  star = "star_red.png"

  footer_logo = "logo.png"